### ISSUE TITLE
[Bug] WaterFall中继了两次连接.

### ISSUE THREAD

**Issue by angushushu** [AkariDream/CubeX-Log#103]
**描述** `Edited by Akkariin`
用户07366822进入服务器后，后台显示[ViaVersion] Duplicate UUID on frontend connection! 然后登录服崩溃.

**复现** `Edited by Akkariin`
在后端服务器还未接纳玩家时 用同名玩家再次加入服务器.

**预期行为** `Editied by Akkariin`
只中继一个相同用户名的连接到后端服务器.

**截图/媒体** `Edited by Akkariin - 省略不必要的内容`
```
[13:54:44] [User Authenticator #117/INFO]: UUID of player 07366822 is a0ea79f8-59c6-305b-87d0-84b62487c339
[13:54:44] [User Authenticator #118/INFO]: UUID of player 07366822 is a0ea79f8-59c6-305b-87d0-84b62487c339
[13:54:44] [Netty Epoll Server IO #1/WARN]: [ViaVersion] Duplicate UUID on frontend connection! (a0ea79f8-59c6-305b-87d0-84b62487c339)
[13:54:44] [Server thread/WARN]: [ViaVersion] Duplicate UUID on frontend connection! (a0ea79f8-59c6-305b-87d0-84b62487c339)
[13:54:44] [Server thread/WARN]: Force-added player with duplicate UUID a0ea79f8-59c6-305b-87d0-84b62487c339
[13:54:44] [Netty Epoll Server IO #1/WARN]: [HolographicDisplays] Unexpected error while modifying the channel pipeline.
java.util.NoSuchElementException: packet_handler
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[patched_1.16.5.jar:git-Purpur-1171]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248) ~[patched_1.16.5.jar:git-Purpur-1171]
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:237) ~[patched_1.16.5.jar:git-Purpur-1171]
	at me.filoghost.holographicdisplays.nms.v1_16_R3.VersionNMSManager.lambda$injectPacketListener$0(VersionNMSManager.java:81) ~[?:?]
	at me.filoghost.holographicdisplays.nms.v1_16_R3.VersionNMSManager.lambda$modifyPipeline$2(VersionNMSManager.java:109) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.16.5.jar:git-Purpur-1171]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.16.5.jar:git-Purpur-1171]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[patched_1.16.5.jar:git-Purpur-1171]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.16.5.jar:git-Purpur-1171]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.16.5.jar:git-Purpur-1171]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[13:54:44] [Server thread/INFO]: 
[13:54:44] [Server thread/INFO]: 07366822 lost connection: AuthX >> [lang]authme.auth.failed.sameip[/lang]
[13:54:44] [Server thread/INFO]: [Pl-Hide-Pro] [DEBUG] Unregistered player: 07366822
```

**附加内容**
~~[类似issue链接，未解决](https://github.com/ViaVersion/ViaVersion/issues/2005)~~ 此问题跟原ViaVersion没有关系.

**Comment by AkariDream** [comment]
FastLogin在BungeeCord上中继了两次玩家的连接. 但是由于某种原因竟然都成功中继到了后端服务器.
```
[13:54:41] [Netty Worker IO Thread #1/INFO]: [/49.248.32.110:35429] <-> InitialHandler has connected
[13:54:41] [Netty Worker IO Thread #2/INFO]: [/49.248.32.110:35428] <-> InitialHandler has connected
[13:54:42] [Netty Worker IO Thread #1/INFO] [FastLogin]: Incoming login request for 07366822 from /49.248.32.110:35429
[13:54:42] [FastLogin Pool Thread #67/INFO] [FastLogin]: Handling player 07366822
[13:54:42] [Netty Worker IO Thread #2/INFO] [FastLogin]: Incoming login request for 07366822 from /49.248.32.110:35428
[13:54:42] [FastLogin Pool Thread #67/INFO] [FastLogin]: Handling player 07366822
[13:54:43] [Netty Worker IO Thread #2/INFO]: [07366822|/49.248.32.110:35428] <-> ServerConnector [AuthX] has connected
[13:54:43] [Netty Worker IO Thread #1/INFO]: [07366822|/49.248.32.110:35429] <-> ServerConnector [AuthX] has connected
```
> (ViaVersion监听的是PreLoginEvent 所以后端XProtect无法以"The same username is already playing on the server!"将玩家踢出服务器)  

正常情况下Waterfall应该会踢出同名在线的玩家. 但是不知为何. Waterfall并没有切断连接.
在一秒钟过后. AkaneField检测出代理 并将其踢出服务器
```
[13:54:44] [AkaneField Pool Thread #422/INFO]: [07366822] disconnected with: 
- 方块叉 | CubeX -
« [X] 玩家的防火墙 [X] »

w! 您被列入黑名单惹! ;w;
如果您认为您没有做错什么 请联系管理员!

黑名单ID  93f9a162
理由  疑似使用VPN或代理

- CubeX -
```
此时 其中一个连接已被切断 但此时WaterFall弹出了一个错误 `No client connected for pending server!`
尽管此时两个同名客户端都还未完全连接到后端服务器. 但是WaterFall在玩家切断了连接之后仍然中继了连接.
`07366822] -> UpstreamBridge has disconnected`
`<-> ServerConnector [AuthX] has disconnected`
`disconnected with: You logged in from another location`
然后后端服务器收到了两个来自同样UUID的玩家的PreLogin. 于是无法处理 便导致服务器崩溃(可能).

> 我暂且不清楚这到底是FastLogin WaterFall本身还是AkaneField的问题. 但我将来会添加一个功能. `same-user-online-kick`

**Comment by AkariDream** [comment]
完整的日志在这里:
```
[13:54:42] [Netty Worker IO Thread #1/INFO] [FastLogin]: Incoming login request for 07366822 from /49.248.32.110:35429
[13:54:42] [FastLogin Pool Thread #67/INFO] [FastLogin]: Handling player 07366822
[13:54:42] [Netty Worker IO Thread #2/INFO] [FastLogin]: Incoming login request for 07366822 from /49.248.32.110:35428
[13:54:42] [FastLogin Pool Thread #67/INFO] [FastLogin]: Handling player 07366822
[13:54:43] [Netty Worker IO Thread #2/INFO]: [07366822|/49.248.32.110:35428] <-> ServerConnector [AuthX] has connected
[13:54:43] [Netty Worker IO Thread #1/INFO]: [07366822|/49.248.32.110:35429] <-> ServerConnector [AuthX] has connected
[13:54:44] [AkaneField Pool Thread #422/INFO]: [07366822] disconnected with: - 方块叉 | CubeX -
« [X] 玩家的防火墙 [X] »

w! 您被列入黑名单惹! ;w;
如果您认为您没有做错什么 请联系管理员!

黑名单ID  93f9a162
理由  疑似使用VPN或代理

- CubeX -
[13:54:44] [Netty Worker IO Thread #1/INFO]: [/49.248.32.110:35429|07366822] -> UpstreamBridge has disconnected
[13:54:44] [Netty Worker IO Thread #1/WARN]: No client connected for pending server!
[13:54:44] [Netty Worker IO Thread #1/INFO]: [07366822|/49.248.32.110:35429] <-> ServerConnector [AuthX] has disconnected
[13:54:44] [Netty Worker IO Thread #2/INFO]: [07366822] disconnected with: You logged in from another location
[13:54:44] [Netty Worker IO Thread #2/INFO]: [/49.248.32.110:35428|07366822] -> UpstreamBridge has disconnected
[13:54:44] [Netty Worker IO Thread #2/INFO]: [/49.248.32.110:35428|07366822] <-> DownstreamBridge <-> [AuthX] has disconnected
```

**Comment by AkariDream** [comment]
@angushushu 请检查新的AkaneField (自行使用maven构建 我没时间给release)
https://github.com/CatMoe/AkaneField/commit/3b5472ed0e98a3ffb57b33bfc32505a81d192df8

**Comment by AkariDream** [comment]
fixed https://github.com/CatMoe/AkaneField/commit/a96b659250debf3e591246d3a5419b26f73b843f
在问题没重复发生之前 应标记为已修复.
